name: Auto Merge PRs

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:        # Allows manual trigger
  pull_request:
    types: [labeled, opened, synchronize]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Automerge PRs
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          mergeMethod: squash
